const NAV={consumer:[["dashboard","Dashboard"],["find","Find Medicine"],["pharmacies","Pharmacies"],["alternatives","Alternatives"],["analytics","Analytics"],["support","Support"]],
 pharmacy:[["dashboard","Dashboard"],["inventory","Inventory"],["forecasting","Forecasting"],["expiry","Expiry Alerts"],["reservations","Reservations"],["analytics","Analytics"]],
 system:[["users","Users"],["vendors","Vendors"],["catalog","Drug Catalog"],["nlp","NLP Monitoring"],["logs","Forecast Logs"]]};
const S={portal:"consumer",view:"dashboard",q:"",history:["Paracetamol 500mg","cheap alternative to Biogesic"],reservations:[],saved:[1,2],inv:{q:"",sort:"name",dir:1,page:1,f:"all"},ph:{f:new Set(),v:"list"},charts:[],map:null};
const hero=(t)=>`<h1>${t}</h1>`;
function nlp(q){const s=q.toLowerCase();let m=DB.meds.find(x=>s.includes(x.brand.toLowerCase())&&x.brand!=="Generic")||DB.meds.find(x=>s.includes(x.name.toLowerCase().split(" ")[0]))||DB.meds.find(x=>s.includes(x.ing.toLowerCase().split(" ")[0]));return m}
function searchBox(){return `<form class="search" id="sf" role="search"><span aria-hidden="true">🔍</span><label class="sr" for="q">Search medicines</label><input id="q" value="${S.q}" placeholder="Search medicine, brand, active ingredient, or describe what you need..."><button type="button" class="ic" style="background:var(--ice);color:var(--teal)" aria-label="Voice search" data-act="mic">🎤</button><span class="loc">📍 Zamboanga City</span><button class="btn">Search</button></form>
<div class="chips">${["cheap alternative to Biogesic","Paracetamol 500mg","medicine with paracetamol","pharmacy near me"].map(c=>`<button data-chip="${c}">${c}</button>`).join("")}</div>`}
function results(){if(!S.q)return"";const s=S.q.toLowerCase();if(s.includes("pharmacy near")){S.q="";go("pharmacies");return""}
 const m=nlp(S.q);if(!m)return `<div class="nlp"><b>No match found.</b> Try a brand, ingredient, or dosage.</div>`;
 let ex=DB.meds.filter(x=>x.id===m.id),alt=DB.meds.filter(x=>x.ing===m.ing&&x.id!==m.id);if(s.includes("cheap"))alt.sort((a,b)=>a.price-b.price);
 return `<div class="nlp"><span class="badge info">NLP MATCH</span> Detected medicine: <b>${m.name}</b> · Active ingredient: <b>${m.ing}</b></div><h2>Exact Matches</h2><div class="grid">${ex.map(x=>medCard(x)).join("")}</div><h2>Generic Alternatives</h2><div class="grid">${alt.map(x=>medCard(x)).join("")||"<p>No alternatives found.</p>"}</div>`}
const V={
consumer:{
 dashboard:()=>hero("Find the right medicine.<br>Find it nearby.")+`<p class="lead">Search medicines, discover generic alternatives, and locate nearby pharmacies with confirmed stock.</p>`+searchBox()+`<div class="kpis">${kpi("🏥","Nearby Pharmacies","24","+4 open now")+kpi("💊","Medicines Available","1,248","Across partner pharmacies")+kpi("🔁","Generic Alternatives","386","Available matches")+kpi("📡","Live Stock Accuracy","98.4%","Real-time sync")}</div><div id="res">${results()}</div>
 <h2>Your overview</h2><div class="two"><div class="panel"><h4>Recent Searches</h4>${S.history.slice(0,5).map(h=>`<button class="btn ghost sm" data-chip="${h}" style="margin:4px 4px 0 0">${h}</button>`).join("")}</div>
 <div class="panel"><h4>Active Reservations</h4>${S.reservations.length?S.reservations.map(r=>`<p>${r.id} — ${r.med} (${r.qty}) @ ${r.ph}</p>`).join(""):'<p class="mut">None yet. Reserve a medicine to see it here.</p>'}</div>
 <div class="panel"><h4>Saved Medicines</h4>${S.saved.map(i=>`<p>${DB.meds[i-1].name} <b>${peso(DB.meds[i-1].price)}</b></p>`).join("")}</div>
 <div class="panel"><h4>Stock Alerts</h4><p>${badge("low")} Amoxicillin 500mg is running low nearby.</p></div></div>`,
 find:()=>hero("Find Medicine")+searchBox()+`<div id="res">${results()}</div>`,
 alternatives:()=>hero("Generic Alternatives")+`<p class="lead">Same active ingredient, lower price.</p><div class="grid" style="margin-top:20px">${DB.meds.filter(m=>m.type==="generic").map(m=>medCard(m)).join("")}</div>`,
 pharmacies:()=>hero("Nearby Pharmacies")+`<div class="filters" role="group" aria-label="Filters">${["Open Now","In Stock","Lowest Price","Nearest","Generic Available"].map(f=>`<button aria-pressed="false" data-f="${f}">${f}</button>`).join("")}<span class="seg"><button aria-pressed="true" data-v="list">List</button><button aria-pressed="false" data-v="map">Map</button></span></div><div class="split" data-v="list"><div class="list" id="plist"></div><div id="map" role="application" aria-label="Pharmacy map"></div></div>`,
 analytics:()=>hero("Demand Trends")+`<div class="two"><div class="panel"><canvas id="c1"></canvas></div><div class="panel"><canvas id="c2"></canvas></div></div>`,
 support:()=>hero("Support")+`<div class="panel"><h4>How can we help?</h4><p>Reservations are held for 2 hours. Contact the pharmacy directly for stock questions.</p><p class="mut"><b>PharmAI helps locate available medicines and alternatives. It does not diagnose conditions or replace advice from a licensed healthcare professional.</b></p></div>`},
pharmacy:{
 dashboard:()=>hero("Pharmacy Dashboard")+`<div class="kpis">${kpi("💊","Total Medicines","1,248","+12 this week")+kpi("✅","In Stock","1,102","88%")+kpi("⚠️","Low Stock","96","Needs review")+kpi("⛔","Out of Stock","50","Restock")+kpi("⏳","Near Expiry","31","Within 30 days")+kpi("📋","Reservations Today","18","6 pending")}</div>${alertPanel()}`,
 inventory:()=>hero("Inventory")+`<div class="tools"><input id="iq" placeholder="Search inventory" aria-label="Search inventory" value="${S.inv.q}"><select id="if" aria-label="Filter"><option value="all">All</option><option value="in">In stock</option><option value="low">Low</option><option value="out">Out</option></select><button class="btn" data-act="add">Add Medicine</button></div><div id="itab"></div>`,
 forecasting:()=>hero("Forecasting")+`<span class="demo">Demo / mock forecasting data — no ML backend yet</span><div class="kpis" style="margin-top:16px">${kpi("📦","Current Stock","18 units","Paracetamol 500mg")+kpi("📈","Predicted Demand","72 units","Next 14 days")+kpi("⏱️","Est. Stockout","3 days","Critical")+kpi("🛒","Replenish","120 units","Recommended")}</div><div class="panel"><canvas id="c1"></canvas></div><p class="lead">Predicted demand spike in 5 days.</p>`+alertPanel(),
 expiry:()=>hero("Smart Expiry / FEFO")+table(["Medicine","Batch","Quantity","Expiry","Days Remaining","Status","Actions"],DB.inventory.slice(0,8).map((r,i)=>{const d=15+i*14;return[r.name,r.batch,r.stock+" units",r.expiry,d+" days",badge(d<30?"out":d<60?"low":"in").replace(/In Stock|Low Stock|Out of Stock/,d<30?"Urgent":d<60?"Approaching":"Safe"),`<button class="btn sm" data-act="toast" data-m="Batch ${r.batch} opened">View Batch</button> <button class="btn sm ghost" data-act="toast" data-m="Discount applied to ${r.batch}">Apply Discount</button>`]})),
 reservations:()=>hero("Reservations")+table(["ID","Medicine","Qty","Status"],[["PH-2041","Paracetamol 500mg","2","Pending"],["PH-2040","Cetirizine 10mg","1","Picked up"],...S.reservations.map(r=>[r.id,r.med,r.qty,"Pending"])]),
 analytics:()=>hero("Analytics")+`<div class="filters">${["7 Days","30 Days","3 Months","6 Months","Custom"].map((f,i)=>`<button aria-pressed="${i==1}" data-act="toast" data-m="Range: ${f}">${f}</button>`).join("")}</div><div class="two"><div class="panel"><canvas id="c1"></canvas></div><div class="panel"><canvas id="c2"></canvas></div></div>`},
system:{
 users:()=>hero("Users")+table(["Name","Role","Status"],DB.users),vendors:()=>hero("Pharmacy Vendors")+table(["Pharmacy","Verified","Distance"],DB.pharmacies.map(p=>[p.name,p.verified?"Yes":"Pending",p.dist+" km"])),
 catalog:()=>hero("Drug Catalog")+table(["Name","Ingredient","Form","Type"],DB.meds.map(m=>[m.name,m.ing,m.form,m.type])),nlp:()=>hero("NLP Monitoring")+table(["Query","Interpretation","Confidence"],DB.nlp),
 logs:()=>hero("Forecast Logs")+`<span class="demo">Mock data</span>`+table(["Run","Medicine","MAPE"],[["#881","Paracetamol 500mg","6.2%"],["#880","Amoxicillin 500mg","8.9%"]])}};
function alertPanel(){return `<h2>Stockout Alerts</h2><div class="panel"><span class="badge bad">✕ CRITICAL</span><h4 style="margin:8px 0">Paracetamol 500mg</h4><p>Current stock: <b>18 units</b> · Predicted demand: <b>72 units</b> · Estimated stockout: <b>3 days</b></p><button class="btn" data-act="go" data-v="inventory">Review Inventory</button></div>`}
function chart(id,type,labels,sets){if(!window.Chart||!$(id))return;S.charts.push(new Chart($(id),{type,data:{labels,datasets:sets},options:{responsive:true,plugins:{legend:{position:"bottom"}}}}))}
function post(){S.charts.forEach(c=>c.destroy());S.charts=[];const k=S.portal+S.view,d=DB.forecast,L=[...d.hist.map((_,i)=>"D"+(i-29)),...d.pred.map((_,i)=>"+"+(i+1))];
 if(S.view==="forecasting")chart("#c1","line",L,[{label:"Historical",data:[...d.hist,...d.pred.map(()=>null)],borderColor:"#0f766e"},{label:"Predicted (mock)",data:[...d.hist.map(()=>null),...d.pred],borderColor:"#22d3ee",borderDash:[6,4]}]);
 if(S.view==="analytics"){chart("#c1","line",["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],[{label:"Sales",data:[120,140,110,170,190,230,160],borderColor:"#0f766e"}]);chart("#c2","doughnut",["Generic","Branded"],[{data:[62,38],backgroundColor:["#2bb5b0","#0a4f55"]}])}
 if(k==="consumerpharmacies")locator();if(S.view==="inventory")inv()}
function locator(){const list=$("#plist"),m=DB.meds[1];const draw=()=>{let r=DB.pharmacies.filter(p=>(!S.ph.f.has("Open Now")||p.open)&&(!S.ph.f.has("In Stock")||p.stock==="in"));if(S.ph.f.has("Nearest"))r.sort((a,b)=>a.dist-b.dist);if(S.ph.f.has("Lowest Price"))r.sort((a,b)=>b.dist-a.dist);list.innerHTML=r.map(p=>pharmCard(p,m)).join("")||"<p>No results.</p>";
 if(S.map){S.map.layers.forEach(l=>l.remove());S.map.layers=r.flatMap(p=>{const best=p.open&&p.stock==="in",out=[];if(best)out.push(L.circleMarker([p.lat,p.lng],{radius:24,color:"#22d3ee",weight:3,fillColor:"#22d3ee",fillOpacity:.18,interactive:false}).addTo(S.map));out.push(L.circleMarker([p.lat,p.lng],{radius:11,color:"#fff",fillOpacity:1,fillColor:{in:"#15803d",low:"#d97706",out:"#b91c1c"}[p.stock]}).addTo(S.map).bindPopup(`<b>${p.name}</b><br>${STAT[p.stock][0]}${best?" · Open now, best match":""}`));return out})}};
 if(window.L){S.map=L.map("map").setView([6.9214,122.0790],13);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(S.map);S.map.layers=[]}else $("#map").innerHTML='<p style="padding:20px">Map needs internet access (Leaflet CDN).</p>';draw();S.ph.draw=draw}
function inv(){const i=S.inv;let r=DB.inventory.filter(x=>x.name.toLowerCase().includes(i.q.toLowerCase())&&(i.f==="all"||st(x)===i.f));r.sort((a,b)=>(a[i.sort]>b[i.sort]?1:-1)*i.dir);const pages=Math.max(1,Math.ceil(r.length/6));i.page=Math.min(i.page,pages);
 const sb=(k,l)=>`<button data-sort="${k}">${l} ${i.sort===k?(i.dir>0?"▲":"▼"):""}</button>`;
 $("#itab").innerHTML=table([sb("name","Medicine"),"Active Ingredient","Batch",sb("stock","Stock"),sb("price","Price"),sb("expiry","Expiry Date"),"Status","Last Updated","Actions"],r.slice((i.page-1)*6,i.page*6).map(x=>[x.name,x.ing,x.batch,x.stock,peso(x.price),x.expiry,badge(st(x)),x.updated,`<button class="btn sm ghost" data-act="edit" data-id="${x.id}">Edit</button> <button class="btn sm" data-act="adj" data-id="${x.id}">Adjust</button>`]))+`<div class="row"><button class="btn sm ghost" data-pg="-1" ${i.page<2?"disabled":""}>Prev</button><span>Page ${i.page} / ${pages}</span><button class="btn sm ghost" data-pg="1" ${i.page>=pages?"disabled":""}>Next</button></div>`}
const st=x=>x.stock===0?"out":x.stock<30?"low":"in";
function go(v){S.view=v;location.hash=v;render()}
function render(){const nav=$("#nav");nav.innerHTML=NAV[S.portal].map(([k,l])=>`<a href="#${k}" ${k===S.view?'aria-current="page"':""}>${l}</a>`).join("");if(!V[S.portal][S.view])S.view=NAV[S.portal][0][0];$("#app").innerHTML=V[S.portal][S.view]();post();$("#bellMenu").innerHTML='<p>⚠️ Paracetamol low at CityMed</p><p>✅ Reservation PH-2040 ready</p><p>🔁 New generic for Cetirizine</p>'}
function doSearch(q){if(!q.trim())return;S.q=q;S.history.unshift(q);S.history=[...new Set(S.history)];render();$("#res")&&$("#res").scrollIntoView({behavior:"smooth"})}
function reserve(mid,pid){let step=1,qty=1,ph=pid?+pid:1;const m=DB.meds[mid-1];const draw=()=>{const p=DB.pharmacies.find(x=>x.id===ph),id=S.rid||(S.rid="RSV-"+Math.floor(10000+Math.random()*89999));
 const bar=`<div class="steps">${[1,2,3,4,5].map(n=>`<i class="${n<=step?"on":""}"></i>`).join("")}</div>`;
 const body={1:`<p><b>${m.name}</b><br>${m.ing} · ${peso(m.price)}</p>`,2:`<label for="ps">Pharmacy</label><br><select id="ps">${DB.pharmacies.filter(x=>x.stock!=="out").map(x=>`<option value="${x.id}" ${x.id===ph?"selected":""}>${x.name} (${x.dist} km)</option>`).join("")}</select>`,3:`<label for="qt">Quantity</label><br><input id="qt" type="number" min="1" max="20" value="${qty}">`,4:`<p>${m.name} × ${qty}<br>${p.name}<br><b>Total ${peso(m.price*qty)}</b></p><p class="mut">Pay at pickup. Held for 2 hours.</p>`,5:`<p><span class="badge ok">✓ Confirmed</span></p><p>ID <b>${id}</b><br>${m.name} × ${qty} — ${peso(m.price*qty)}<br>Pickup: ${p.name}, ${p.addr}<br>Expires in 2 hours</p>`}[step];
 openModal(`${bar}<h3 id="mt">${["","Select Medicine","Select Pharmacy","Select Quantity","Confirm Reservation","Reservation Success"][step]}</h3>${body}<div class="row"><button class="btn ghost" data-m="x">${step===5?"Close":"Cancel"}</button>${step<5?`<button class="btn" data-m="next">${step===4?"Confirm":"Next"}</button>`:""}</div>`);
 $("#mbox").onclick=e=>{const b=e.target.closest("[data-m]");if(!b)return;if(b.dataset.m==="x"){S.rid=null;return closeModal()}if($("#ps"))ph=+$("#ps").value;if($("#qt"))qty=Math.max(1,+$("#qt").value||1);step++;if(step===5){S.reservations.push({id,med:m.name,qty,ph:p.name});toast("Reservation "+id+" confirmed")}draw()}};draw()}
function formModal(x){openModal(`<h3 id="mt">${x?"Edit":"Add"} Medicine</h3><p><label>Name<br><input id="fn" value="${x?x.name:""}"></label></p><p><label>Stock<br><input id="fs" type="number" value="${x?x.stock:0}"></label></p><p><label>Price<br><input id="fp" type="number" step=".01" value="${x?x.price:0}"></label></p><div class="row"><button class="btn ghost" data-m="x">Cancel</button><button class="btn" data-m="ok">Save</button></div>`);
 $("#mbox").onclick=e=>{const b=e.target.closest("[data-m]");if(!b)return;if(b.dataset.m==="ok"){const n=$("#fn").value.trim();if(!n)return toast("Name required");const o=x||{id:Date.now(),ing:n.split(" ")[0],batch:"P-"+Math.floor(3000+Math.random()*999),expiry:"2027-03-15"};Object.assign(o,{name:n,stock:+$("#fs").value,price:+$("#fp").value,updated:"just now"});if(!x)DB.inventory.unshift(o);inv();toast("Saved")}closeModal()}}
document.addEventListener("click",e=>{const t=e.target,c=t.closest("[data-chip]");if(c)return doSearch(c.dataset.chip);
 const a=t.closest("[data-act]");if(a){const d=a.dataset;if(d.act==="reserve")reserve(+d.id,d.ph);if(d.act==="detail"){const m=DB.meds[d.id-1];openModal(`<h3 id="mt">${m.name}</h3><p>${m.brand} · ${m.ing} · ${m.dose} · ${m.form}<br><b>${peso(m.price)}</b> · ${badge("in")}</p><p class="mut">Available at ${DB.pharmacies.filter(p=>p.stock!=="out").map(p=>p.name).join(", ")}.</p><p class="mut"><b>PharmAI helps locate available medicines and alternatives. It does not diagnose conditions or replace advice from a licensed healthcare professional.</b></p><button class="btn" data-act="close">Close</button>`)}
 if(d.act==="pharm"){const p=DB.pharmacies[d.id-1];openModal(`<h3 id="mt">${p.name} ${p.verified?"✔ Verified":""}</h3><p>${p.addr}<br>${p.phone}<br>${p.hours}</p>${table(["Medicine","Price","Stock"],DB.meds.slice(0,4).map(m=>[m.name,peso(m.price),"In stock"]))}<p class="mut">Inventory updated 12 min ago</p><button class="btn" data-act="reserve" data-id="2" data-ph="${p.id}">Reserve Medicine</button>`)}
 if(d.act==="close")closeModal();if(d.act==="toast")toast(d.m);if(d.act==="mic")toast("Voice search is a demo placeholder");if(d.act==="go")go(d.v);if(d.act==="add")formModal();if(d.act==="edit")formModal(DB.inventory.find(x=>x.id==d.id));
 if(d.act==="adj"){const x=DB.inventory.find(x=>x.id==d.id);x.stock=Math.max(0,x.stock+10);x.updated="just now";inv();toast(x.name+" stock +10")}return}
 const f=t.closest("[data-f]");if(f){const on=f.getAttribute("aria-pressed")!=="true";f.setAttribute("aria-pressed",on);on?S.ph.f.add(f.dataset.f):S.ph.f.delete(f.dataset.f);S.ph.draw()}
 const v=t.closest("[data-v]");if(v&&v.closest(".seg")){$(".split").dataset.v=v.dataset.v;$$(".seg button").forEach(b=>b.setAttribute("aria-pressed",b===v));S.map&&setTimeout(()=>S.map.invalidateSize(),50)}
 const so=t.closest("[data-sort]");if(so){S.inv.dir=S.inv.sort===so.dataset.sort?-S.inv.dir:1;S.inv.sort=so.dataset.sort;inv()}
 const pg=t.closest("[data-pg]");if(pg){S.inv.page+=+pg.dataset.pg;inv()}
 if(t.id==="modal")closeModal();
 const dd=t.closest(".dd");$$(".menu").forEach(m=>{if(!dd||!dd.contains(m))m.hidden=true});if(t.closest("#bell"))$("#bellMenu").hidden=!$("#bellMenu").hidden;if(t.closest("#usr"))$("#usrMenu").hidden=!$("#usrMenu").hidden;
 if(t.closest("#burger")){const o=$("#nav").classList.toggle("open");$("#burger").setAttribute("aria-expanded",o)}else if(t.closest("#nav a"))$("#nav").classList.remove("open")});
document.addEventListener("submit",e=>{if(e.target.id==="sf"){e.preventDefault();doSearch($("#q").value)}});
document.addEventListener("input",e=>{if(e.target.id==="iq"){S.inv.q=e.target.value;S.inv.page=1;inv()}});
document.addEventListener("change",e=>{if(e.target.id==="if"){S.inv.f=e.target.value;S.inv.page=1;inv()}});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
$("#portal").onchange=e=>{S.portal=e.target.value;S.view=NAV[S.portal][0][0];location.hash=S.view;render()};
window.onhashchange=()=>{const h=location.hash.slice(1);if(h&&h!==S.view&&V[S.portal][h]){S.view=h;render()}};
render();
